title: My personal blog - Dominic Ma
email: dominicma@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/wanderingdominic.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Dominic Ma # add your name
author-pic: dominic-face.JPG
about-author: I'm Dominica from Shanghai, China, Chinese name MA Xiaolong. I once worked as a project manager for IoT products in GE Lighting, and recently I moved to a new role Partner Architect in Intel IoTG for Computer Vision solutions.
# Contact links
email: dominicma@qq.com # Add your Email address
phone: 8615091773343 # Add your Phone number
website: # Add your website, do not add http://
linkedin: xiaolong--ma # Add your Linkedin handle
github: wanderingdominic # Add your Github handle
twitter:  # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: wanderingdominic # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: mr-brown # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
